language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - redis-server

services:
- redis-server

install:
- pip install -r requirements-test.txt

script:
- sudo /etc/init.d/redis-server stop
- make lint
- make test

# deploy:
#   provider: pypi
#   user: "Your username"
#   password: "Your password"
